linux /vmlinuz
fdt /dtbs/qcom/msm8916-generic-uf02.dtb
# OctoPrint profile (uz801v3, no LTE modem, no video decode, WiFi kept):
# fdt /dtbs/qcom/msm8916-yiming-uz801v3-octoprint.dtb
append earlycon root=PARTUUID=a7ab80e8-e9d1-e8cd-f157-93f69b1d141e console=ttyMSM0,115200 no_framebuffer=true rw rootwait
